import { loadThreat } from '@/lib/agent/memory';
import { notFound } from 'next/navigation';

export const dynamic = 'force-dynamic';

interface Props {
  params: Promise<{ id: string }>;
}

export default async function ThreatPage({ params }: Props) {
  const { id } = await params;
  const threat = await loadThreat(id);

  if (!threat) notFound();

  const riskColors: Record<string, string> = {
    critical: 'bg-red-500/15 text-red-400 border-red-500/30',
    high: 'bg-orange-500/15 text-orange-400 border-orange-500/30',
    medium: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    low: 'bg-green-500/15 text-green-400 border-green-500/30',
    none: 'bg-gray-500/15 text-gray-400 border-gray-500/30',
  };

  const riskLevel = threat.level;
  const riskClass = riskColors[riskLevel] ?? riskColors.medium;

  return (
    <div className="min-h-screen bg-space-dark text-white">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className={`inline-block px-3 py-1 rounded border text-xs font-semibold uppercase mb-4 ${riskClass}`}>
          {riskLevel} risk
        </div>
        <h1 className="text-3xl font-semibold mb-2">{threat.asteroidId}</h1>
        <p className="text-gray-400 text-sm mb-8">Threat Assessment &bull; {threat.assessedAt}</p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-200 mb-3">Summary</h2>
          <p className="text-gray-300 leading-relaxed">{threat.summary}</p>
        </section>

        {threat.factors.length > 0 && (
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-200 mb-3">Risk Factors</h2>
            <ul className="space-y-2">
              {threat.factors.map((factor, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-300">
                  <span className="text-amber-400 mt-1">!</span>
                  <span>{factor}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        <div className="border-t border-gray-800 mt-8 pt-4 text-xs text-gray-500">
          Generated by Claude Agent &bull; Asteroid ID: {id}
        </div>
      </div>
    </div>
  );
}
