import { loadBriefing } from '@/lib/agent/memory';

export const dynamic = 'force-dynamic';

export default async function BriefingsPage() {
  const briefing = await loadBriefing();

  return (
    <div className="min-h-screen bg-space-dark text-white">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-semibold mb-2">NEO Daily Briefing</h1>
        <p className="text-gray-400 text-sm mb-8">Generated by AstroWatch AI Agent</p>

        {!briefing ? (
          <div className="text-gray-500">No briefing available yet. The agent runs every 4 hours.</div>
        ) : (
          <div className="space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-gray-200 mb-3">Summary</h2>
              <p className="text-gray-300 leading-relaxed">{briefing.summary}</p>
            </section>

            {briefing.highlights.length > 0 && (
              <section>
                <h2 className="text-xl font-semibold text-gray-200 mb-3">Highlights</h2>
                <ul className="space-y-2">
                  {briefing.highlights.map((h, i) => (
                    <li key={i} className="flex items-start gap-2 text-gray-300">
                      <span className="text-blue-400 mt-1">&bull;</span>
                      <span>{h}</span>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            <div className="border-t border-gray-800 pt-4 text-xs text-gray-500">
              Generated by Claude Agent &bull; {briefing.date}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
